INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:17] "GET / HTTP/1.1" 200 -
DEBUG:root:2021-08-20 14:53:18.881000, Article "2020 CNCF Annual Report" retrived
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:18] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:20] "GET /create HTTP/1.1" 200 -
DEBUG:root:2021-08-20 14:53:21.973000, A new article was created.
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:21] "POST /create HTTP/1.1" 302 -
DEBUG:root:2021-08-20 14:53:22.305000, A new article was created.
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:22] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:26] "GET /health HTTP/1.1" 404 -
INFO:app:Status request successfull
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:32] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successfull
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in metrics
    logging.debug("{},{} endpoint was reached.".format(datetime.datetime.now()),request.path)
IndexError: tuple index out of range
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:53:36] "GET /metrics HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in metrics
    logging.debug("{},{} endpoint was reached.".format(datetime.datetime.now()),response.path)
IndexError: tuple index out of range
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:54:47] "GET /metrics HTTP/1.1" 500 -
INFO:app:Metrics request successfull
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in metrics
    logging.debug("{},{} endpoint was reached.".format(datetime.datetime.now()),response.path)
IndexError: tuple index out of range
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:54:48] "GET /metrics HTTP/1.1" 500 -
INFO:app:Metrics request successfull
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Users\Madai\anaconda3\envs\py2\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in metrics
    logging.debug("{},{} endpoint was reached.".format(datetime.datetime.now()),response.path)
IndexError: tuple index out of range
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:54:49] "GET /metrics HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
DEBUG:root:2021-08-20 14:55:11.499000,Endpoint was reached.
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:55:11] "GET /metrics HTTP/1.1" 200 -
INFO:app:Metrics request successfull
DEBUG:root:2021-08-20 14:55:12.471000,Endpoint was reached.
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:55:12] "GET /metrics HTTP/1.1" 200 -
DEBUG:root:2021-08-20 14:55:15.931000, Article "2020 CNCF Annual Report" retrived
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:55:15] "GET /1 HTTP/1.1" 200 -
DEBUG:root:2021-08-20 14:55:16.919000, Article "KubeCon + CloudNativeCon 2021" retrived
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:55:16] "GET /2 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:55:18] "GET / HTTP/1.1" 200 -
INFO:app:Metrics request successfull
DEBUG:root:2021-08-20 14:55:23.737000,Endpoint was reached.
INFO:werkzeug:127.0.0.1 - - [20/Aug/2021 14:55:23] "GET /metrics HTTP/1.1" 200 -
